### ISSUE TITLE
f.getClientRects error with jquery 3.0.0

### ISSUE THREAD

**Issue by pachydermcreation** [qTip2/qTip2#797]
jQuery.Deferred exception: f.getClientRects is not a function TypeError: f.getClientRects is not a function
    at r.offset (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:4:20004)
    at Object.R.viewport (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:4:6791)
    at e.z.reposition (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:13899)
    at e.z.toggle (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:16971)
    at http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:6894
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29588)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js:2:29902) undefined

jQuery.Deferred exception: elem.getClientRects is not a function TypeError: elem.getClientRects is not a function
    at jQuery.offset (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.js:9779:14)
    at Object.R.viewport (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:4:6791)
    at e.z.reposition (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:13899)
    at e.z.toggle (http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:16971)
    at http://cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js:3:6894
    at mightThrow (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.js:3505:29)
    at process (https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.js:3573:12) undefined

**Comment by ciel** [comment]
Any update on this?

**Comment by drumsibumsi** [comment]
Same here using jQuery 3.1.0. No issues with jQuery 2.2.2.

**Comment by AgamlaRage** [comment]
Thx! Works for me !

**Comment by spookyUnknownUser** [comment]
Anyway to still have the viewport config and use jQuery 3.x?

**Comment by samdasoxide** [comment]
I had the same issue with it using [counterup](https://www.npmjs.com/package/counterup). jQuery recomends installing [jquery-migrate](https://www.npmjs.com/package/jquery-migrate) to address this breakages from their [blog](http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/).
